# Generated by Django 3.1.2 on 2020-12-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addelder',
            name='elder',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addelder',
            name='volunteer',
            field=models.IntegerField(default=0),
        ),
    ]
