# Generated by Django 3.1.3 on 2020-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=50)),
                ('service_done', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('custom_feedback', models.TextField(blank=True)),
            ],
        ),
    ]
