# Generated by Django 3.1.2 on 2020-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201212_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteElder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder', models.IntegerField(default=0)),
                ('volunteer', models.CharField(max_length=150)),
            ],
        ),
    ]
