# Generated by Django 2.2.7 on 2020-11-09 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201027_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('elder_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('elder_name', models.CharField(max_length=50)),
                ('elder_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(110)])),
                ('phone_no', models.CharField(max_length=14)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Address')),
            ],
        ),
    ]
