# Generated by Django 3.1.2 on 2020-10-31 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201027_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('elder_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('elder_name', models.CharField(max_length=50)),
                ('elder_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(110)])),
                ('phone_no', models.CharField(max_length=14)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.address')),
            ],
        ),
    ]
