# Generated by Django 2.2.7 on 2020-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_elder'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
