# Generated by Django 3.1.2 on 2020-11-04 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201031_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
