# Generated by Django 3.1.2 on 2020-11-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201104_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='profile_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
