# Generated by Django 3.1.2 on 2020-11-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201106_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elder',
            name='elder_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
