# Generated by Django 3.1.3 on 2020-11-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201106_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.address'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='biography',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='services_available',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
