# Generated by Django 2.2.7 on 2020-11-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201110_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='services_available',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Service'),
        ),
    ]
