# Generated by Django 3.1.3 on 2020-11-10 20:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201111_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=None, size=None),
        ),
    ]
