# Generated by Django 3.1.3 on 2020-11-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201111_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_name',
            field=models.CharField(max_length=50),
        ),
    ]
