# Generated by Django 3.1.3 on 2020-11-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201111_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='services_available',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
    ]
