# Generated by Django 3.1.3 on 2020-11-10 21:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201111_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
